### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by luanjunqing** [realpython/image-fingerprinting#1]
when i run python search.py —dataset images —shelve db.shelve —query images/5134e0c2-34d3-40b6-9473-98de8be16c67.jpg

there`s some problem like this

![qq 20150518231339](https://cloud.githubusercontent.com/assets/3974264/7683739/9876b2ba-fdb3-11e4-876c-c1fb348049fe.png)

**Comment by mjhea0** [comment]
Can I see your code?

**Comment by luanjunqing** [comment]
The code was i cloned from the master branch,i`m not change it

**Comment by luanjunqing** [comment]
![qq 20150519105007](https://cloud.githubusercontent.com/assets/3974264/7694665/0cdf9894-fe16-11e4-9062-877c8b388419.png)

**Comment by luanjunqing** [comment]
the code was i download from your blog```

**Comment by luanjunqing** [comment]
then i cloned the code from the github,then run gather.py,there`s no error this time,but nothing happened,don`t it generate a images folder?and the output.csv is empty,the screenshot like this,how to use it?thx
![qq 20150519122837](https://cloud.githubusercontent.com/assets/3974264/7695468/b20a16c6-fe22-11e4-9305-d9d5d466e519.png)
![qq 20150519122856](https://cloud.githubusercontent.com/assets/3974264/7695469/b20ebcee-fe22-11e4-83b3-5a6a6821978e.png)

**Comment by jrosebr1** [comment]
@luanjunqing Which version of OpenCV are you using?

**Comment by luanjunqing** [comment]
I guess the version is 3.0.0
![qq 20150519182656](https://cloud.githubusercontent.com/assets/3974264/7700947/402aa11e-fe55-11e4-9220-29e220ab3411.png)

**Comment by jrosebr1** [comment]
Downgrade to OpenCV 2.4.X and that will take care of the errors you are getting. OpenCV 3 is in Release Candidate phase and there are still some kinks and backward compatibility issues to be resolved. As I said, revert to OpenCV 2.4.X (where X >= 8) and everything will work perfectly.

**Comment by mjhea0** [comment]
Thanks, @jrosebr1. If you still have problems, @luanjunqing, please open a new ticket.

**Comment by luanjunqing** [comment]
I`ll try it later,and thx a lot bro :D
